[project]
name = "rokenbok-webserver"
version = "0.4.1"
readme = "README.md"
requires-python = ">=3.14.3, <3.15"
dependencies = [
    "argparse",
    "colorlog",
    "Flask",
    "Flask-Session",
    "Flask-SocketIO",
    "pyinstaller",
    "pyserial",
    "PyYAML",
    "requests",
]

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "ruff>=0.16.10",
]
docs = [
    "sphinx",
    "furo"
]

[tool.ruff]
line-length = 140
