[webserver]

# IP address the server will listen on
listen_ip = 0.0.0.0

# Port the server will listen on
listen_port = 5000

# Try and open the configured port automatically via UPnP
upnp = false

# Verbosity of the server logs
log_level = WARNING

# Show flask specific logs
flask_logs = false

# Configure video streams
enable_video = false

[smartport_arduino]

# COM port or device path of the SmartPort Arduino
serial_port = 

# Enabled SmartPort Arduino vehicle numbers and names (15 max)
[smartport_arduino.vehicles]
1 = 
2 = 
3 = 
4 = 
5 = 
6 = 
7 = 
8 = 

# Available video stream names and URLs (no maximum)
[video_streams]
Camera 1 = 
Camera 2 = 
