name: Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
            ext: .exe
          - os: macos-26
            platform: mac
            arch: arm64
            ext: ""
          - os: macos-26-intel
            platform: mac
            arch: x86_64
            ext: ""

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          check-latest: true 

      - name: Build
        run: |
          if [[ "${{ matrix.platform }}" == "mac" ]]; then
            ARCH_FLAG="--target-arch ${{ matrix.arch }}"
          fi
          pip install -r requirements.txt
          pyinstaller rokenbok_webserver.spec $ARCH_FLAG
          mkdir staging
          cp dist/rokenbok_webserver${{ matrix.ext }} rokenbok_webserver.ini staging/
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: rokenbok-webserver-${{ matrix.platform }}-${{ matrix.arch }}
          path: staging/
