name: Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          check-latest: true 

      - name: Build
        run: | 
          pip install -r requirements.txt
          pyinstaller rokenbok_webserver.spec
          mkdir staging
          cp dist/rokenbok_webserver.* rokenbok_webserver.ini staging/
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: rokenbok-webserver-windows
          path: staging/
