name: Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: win
            go2rtc: "https://github.com/AlexxIT/go2rtc/releases/download/v1.9.14/go2rtc_win64.zip"
          - os: macos-latest
            name: mac
            go2rtc: "https://github.com/AlexxIT/go2rtc/releases/download/v1.9.14/go2rtc_mac_arm64.zip"
          - os: macos-15-intel
            name: mac_intel
            go2rtc: "https://github.com/AlexxIT/go2rtc/releases/download/v1.9.14/go2rtc_mac_amd64.zip"

    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'
          check-latest: true 

      - name: Build
        env:
          REF_NAME: ${{ github.ref_name }}
          GO2RTC_URL: ${{ matrix.go2rtc }}
        run: | 
          mkdir bin staging
          curl -L "$GO2RTC_URL" -o go2rtc.zip
          unzip -o go2rtc.zip -d bin/
          EXECUTABLE=$(ls bin/go2rtc*)
          mv "$EXECUTABLE" "${EXECUTABLE%.*}"
          chmod +x bin/go2rtc
          pip install -r requirements.txt
          pyinstaller rokenbok_webserver.spec
          cp dist/rokenbok_webserver* rokenbok_webserver.ini staging/
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: rokenbok_webserver_${{ env.BUILD_STRING }}_${{ matrix.name }}
          path: staging/
